//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomActions.Localization {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CustomActionsStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CustomActionsStrings() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CustomActions.Localization.CustomActionsStrings", typeof(CustomActionsStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add a .
        /// </summary>
        internal static string AddA {
            get {
                return ResourceManager.GetString("AddA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add this Registry Key : .
        /// </summary>
        internal static string AddThisRegKey {
            get {
                return ResourceManager.GetString("AddThisRegKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à and kill the process if it run more than .
        /// </summary>
        internal static string AndKillProcessIfItRunMoreThan {
            get {
                return ResourceManager.GetString("AndKillProcessIfItRunMoreThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à and store the return code to the variable..
        /// </summary>
        internal static string AndStoreReturnCodeToVariable {
            get {
                return ResourceManager.GetString("AndStoreReturnCodeToVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Automatic.
        /// </summary>
        internal static string Automatic {
            get {
                return ResourceManager.GetString("Automatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change the Registry Data : .
        /// </summary>
        internal static string ChangeRegData {
            get {
                return ResourceManager.GetString("ChangeRegData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change the starting mode of .
        /// </summary>
        internal static string ChangeTheStartingModeOf {
            get {
                return ResourceManager.GetString("ChangeTheStartingModeOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à configured.
        /// </summary>
        internal static string Configured {
            get {
                return ResourceManager.GetString("Configured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Copy the file .
        /// </summary>
        internal static string CopyTheFile {
            get {
                return ResourceManager.GetString("CopyTheFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create the folder .
        /// </summary>
        internal static string CreateTheFolder {
            get {
                return ResourceManager.GetString("CreateTheFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create the text file .
        /// </summary>
        internal static string CreateTheTextFile {
            get {
                return ResourceManager.GetString("CreateTheTextFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create a shortcut named .
        /// </summary>
        internal static string CreateThisShortcut {
            get {
                return ResourceManager.GetString("CreateThisShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete .
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete the file .
        /// </summary>
        internal static string DeleteTheFile {
            get {
                return ResourceManager.GetString("DeleteTheFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete the folder .
        /// </summary>
        internal static string DeleteTheFolder {
            get {
                return ResourceManager.GetString("DeleteTheFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete this registry key : .
        /// </summary>
        internal static string DeleteThisRegKey {
            get {
                return ResourceManager.GetString("DeleteThisRegKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete the scheduled task : .
        /// </summary>
        internal static string DeleteThisTask {
            get {
                return ResourceManager.GetString("DeleteThisTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Allows to add a Registry Key..
        /// </summary>
        internal static string DescriptionAddRegKeyAction {
            get {
                return ResourceManager.GetString("DescriptionAddRegKeyAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Allows to add a Registry Value..
        /// </summary>
        internal static string DescriptionAddRegValueAction {
            get {
                return ResourceManager.GetString("DescriptionAddRegValueAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Allows to change a Data in a Registry Value..
        /// </summary>
        internal static string DescriptionChangeRegDataAction {
            get {
                return ResourceManager.GetString("DescriptionChangeRegDataAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Allows to change the starting mode of a service..
        /// </summary>
        internal static string DescriptionChangeServiceAction {
            get {
                return ResourceManager.GetString("DescriptionChangeServiceAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Allows to copy a file..
        /// </summary>
        internal static string DescriptionCopyFileAction {
            get {
                return ResourceManager.GetString("DescriptionCopyFileAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Allows to create a folder..
        /// </summary>
        internal static string DescriptionCreateFolderAction {
            get {
                return ResourceManager.GetString("DescriptionCreateFolderAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Allow to create a shortcut.
        /// </summary>
        internal static string DescriptionCreateShortcutAction {
            get {
                return ResourceManager.GetString("DescriptionCreateShortcutAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Allows to create a text file..
        /// </summary>
        internal static string DescriptionCreateTextFileAction {
            get {
                return ResourceManager.GetString("DescriptionCreateTextFileAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Allows to delete a file..
        /// </summary>
        internal static string DescriptionDeleteFileAction {
            get {
                return ResourceManager.GetString("DescriptionDeleteFileAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Allows to delete a folder..
        /// </summary>
        internal static string DescriptionDeleteFolderAction {
            get {
                return ResourceManager.GetString("DescriptionDeleteFolderAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Allow to delete a Registry Key..
        /// </summary>
        internal static string DescriptionDeleteRegKeyAction {
            get {
                return ResourceManager.GetString("DescriptionDeleteRegKeyAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Allows to delete a Registry Value..
        /// </summary>
        internal static string DescriptionDeleteRegValueAction {
            get {
                return ResourceManager.GetString("DescriptionDeleteRegValueAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Allow to delete a scheduled task.
        /// </summary>
        internal static string DescriptionDeleteTask {
            get {
                return ResourceManager.GetString("DescriptionDeleteTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Allows to execute a file..
        /// </summary>
        internal static string DescriptionExecutableAction {
            get {
                return ResourceManager.GetString("DescriptionExecutableAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à import a .reg file..
        /// </summary>
        internal static string DescriptionImportRegFileAction {
            get {
                return ResourceManager.GetString("DescriptionImportRegFileAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Allow to install a MSI application.
        /// </summary>
        internal static string DescriptionInstallMsi {
            get {
                return ResourceManager.GetString("DescriptionInstallMsi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Allows to kill a process..
        /// </summary>
        internal static string DescriptionKillProcessAction {
            get {
                return ResourceManager.GetString("DescriptionKillProcessAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Allows to reboot the computer..
        /// </summary>
        internal static string DescriptionRebootAction {
            get {
                return ResourceManager.GetString("DescriptionRebootAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Allows to register a DLL..
        /// </summary>
        internal static string DescriptionRegisterDLLAction {
            get {
                return ResourceManager.GetString("DescriptionRegisterDLLAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Allows to rename a file..
        /// </summary>
        internal static string DescriptionRenameFileAction {
            get {
                return ResourceManager.GetString("DescriptionRenameFileAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Alllows to rename a folder..
        /// </summary>
        internal static string DescriptionRenameFolderAction {
            get {
                return ResourceManager.GetString("DescriptionRenameFolderAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Allows to rename a Registry key..
        /// </summary>
        internal static string DescriptionRenameRegKeyAction {
            get {
                return ResourceManager.GetString("DescriptionRenameRegKeyAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Allows to rename a Registry Value..
        /// </summary>
        internal static string DescriptionRenameRegValueAction {
            get {
                return ResourceManager.GetString("DescriptionRenameRegValueAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Allows to set a return code to send when finished..
        /// </summary>
        internal static string DescriptionReturnCodeAction {
            get {
                return ResourceManager.GetString("DescriptionReturnCodeAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Allows to run a Powershell script..
        /// </summary>
        internal static string DescriptionRunPowershellScriptAction {
            get {
                return ResourceManager.GetString("DescriptionRunPowershellScriptAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Allows to run a VbScript..
        /// </summary>
        internal static string DescriptionRunVBScriptAction {
            get {
                return ResourceManager.GetString("DescriptionRunVBScriptAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Allows to shutdown the computer..
        /// </summary>
        internal static string DescriptionShutdownAction {
            get {
                return ResourceManager.GetString("DescriptionShutdownAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Allows to start a service..
        /// </summary>
        internal static string DescriptionStartServiceAction {
            get {
                return ResourceManager.GetString("DescriptionStartServiceAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Allows to stop a service..
        /// </summary>
        internal static string DescriptionStopServiceAction {
            get {
                return ResourceManager.GetString("DescriptionStopServiceAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Allow to uninstall a MSI product by knowing his Guid..
        /// </summary>
        internal static string DescriptionUinstallMsiProductByGuid {
            get {
                return ResourceManager.GetString("DescriptionUinstallMsiProductByGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Allow to uninstall MSI applications by knowing their name.
        /// </summary>
        internal static string DescriptionUninstallMsiProductByNameAction {
            get {
                return ResourceManager.GetString("DescriptionUninstallMsiProductByNameAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Allows to unregister a DLL..
        /// </summary>
        internal static string DescriptionUnregisterDLLAction {
            get {
                return ResourceManager.GetString("DescriptionUnregisterDLLAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Allows to Unregister a service..
        /// </summary>
        internal static string DescriptionUnregisterServiceAction {
            get {
                return ResourceManager.GetString("DescriptionUnregisterServiceAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Allows to wait an amount of time..
        /// </summary>
        internal static string DescriptionWaitAction {
            get {
                return ResourceManager.GetString("DescriptionWaitAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disable.
        /// </summary>
        internal static string Disable {
            get {
                return ResourceManager.GetString("Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Execute the file .
        /// </summary>
        internal static string ExecuteTheFile {
            get {
                return ResourceManager.GetString("ExecuteTheFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Execute the Powershell script .
        /// </summary>
        internal static string ExecuteThePowershellScript {
            get {
                return ResourceManager.GetString("ExecuteThePowershellScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Execute the VbScript .
        /// </summary>
        internal static string ExecuteTheVbScript {
            get {
                return ResourceManager.GetString("ExecuteTheVbScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Import the file : .
        /// </summary>
        internal static string ImportTheFile {
            get {
                return ResourceManager.GetString("ImportTheFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  in .
        /// </summary>
        internal static string In {
            get {
                return ResourceManager.GetString("In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Install .
        /// </summary>
        internal static string Install {
            get {
                return ResourceManager.GetString("Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  into .
        /// </summary>
        internal static string Into {
            get {
                return ResourceManager.GetString("Into", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Kill the process : .
        /// </summary>
        internal static string KillProcess {
            get {
                return ResourceManager.GetString("KillProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Manual.
        /// </summary>
        internal static string Manual {
            get {
                return ResourceManager.GetString("Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à minutes.
        /// </summary>
        internal static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à misconfigured.
        /// </summary>
        internal static string Misconfigured {
            get {
                return ResourceManager.GetString("Misconfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No help available for this Action..
        /// </summary>
        internal static string NoHelpAvailable {
            get {
                return ResourceManager.GetString("NoHelpAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à not configured.
        /// </summary>
        internal static string NotConfigured {
            get {
                return ResourceManager.GetString("NotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reboot the computer..
        /// </summary>
        internal static string Reboot {
            get {
                return ResourceManager.GetString("Reboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Register this DLL : .
        /// </summary>
        internal static string RegisterDLL {
            get {
                return ResourceManager.GetString("RegisterDLL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  registry value named .
        /// </summary>
        internal static string RegValueNamed {
            get {
                return ResourceManager.GetString("RegValueNamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rename the file.
        /// </summary>
        internal static string RenameTheFile {
            get {
                return ResourceManager.GetString("RenameTheFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rename the folder .
        /// </summary>
        internal static string RenameTheFolder {
            get {
                return ResourceManager.GetString("RenameTheFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rename this Registry Key : .
        /// </summary>
        internal static string RenameThisRegKey {
            get {
                return ResourceManager.GetString("RenameThisRegKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rename this Registry value : .
        /// </summary>
        internal static string RenameThisRegValue {
            get {
                return ResourceManager.GetString("RenameThisRegValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Always restart.
        /// </summary>
        internal static string RestartLevel_Force {
            get {
                return ResourceManager.GetString("RestartLevel_Force", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No restart.
        /// </summary>
        internal static string RestartLevel_None {
            get {
                return ResourceManager.GetString("RestartLevel_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prompt user if needed.
        /// </summary>
        internal static string RestartLevel_Prompt {
            get {
                return ResourceManager.GetString("RestartLevel_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Always return the code : .
        /// </summary>
        internal static string ReturnStaticCode {
            get {
                return ResourceManager.GetString("ReturnStaticCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Return the code previously stored in the variable..
        /// </summary>
        internal static string ReturnVariable {
            get {
                return ResourceManager.GetString("ReturnVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à seconds.
        /// </summary>
        internal static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Shutdown the computer..
        /// </summary>
        internal static string Shutdown {
            get {
                return ResourceManager.GetString("Shutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start the service : .
        /// </summary>
        internal static string StartTheService {
            get {
                return ResourceManager.GetString("StartTheService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stop the service : .
        /// </summary>
        internal static string StopTheService {
            get {
                return ResourceManager.GetString("StopTheService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Xml Element &apos;{0}&apos; has not been match with any properties of &apos;{1}&apos;.
        /// </summary>
        internal static string TheXmlElementHasNotBeenMatchWithProperty {
            get {
                return ResourceManager.GetString("TheXmlElementHasNotBeenMatchWithProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This Action does nothing..
        /// </summary>
        internal static string ThisActionDoesNothing {
            get {
                return ResourceManager.GetString("ThisActionDoesNothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This Action is.
        /// </summary>
        internal static string ThisActionIs {
            get {
                return ResourceManager.GetString("ThisActionIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This action refers to a user profile..
        /// </summary>
        internal static string ThisActionRefersToUserProfile {
            get {
                return ResourceManager.GetString("ThisActionRefersToUserProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  to .
        /// </summary>
        internal static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Basic UI.
        /// </summary>
        internal static string UILevel_Base {
            get {
                return ResourceManager.GetString("UILevel_Base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Full UI.
        /// </summary>
        internal static string UILevel_Full {
            get {
                return ResourceManager.GetString("UILevel_Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No UI.
        /// </summary>
        internal static string UILevel_None {
            get {
                return ResourceManager.GetString("UILevel_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reduced UI.
        /// </summary>
        internal static string UILevel_Reduced {
            get {
                return ResourceManager.GetString("UILevel_Reduced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Uninstall the application : {0} with parameters {1}.
        /// </summary>
        internal static string UninstallThisMsiApplication {
            get {
                return ResourceManager.GetString("UninstallThisMsiApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unregister the service : .
        /// </summary>
        internal static string UnregisterTheService {
            get {
                return ResourceManager.GetString("UnregisterTheService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unregister this DLL : .
        /// </summary>
        internal static string UnregisterThisDLL {
            get {
                return ResourceManager.GetString("UnregisterThisDLL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Wait.
        /// </summary>
        internal static string Wait {
            get {
                return ResourceManager.GetString("Wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  which content .
        /// </summary>
        internal static string whichContent {
            get {
                return ResourceManager.GetString("whichContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  which target .
        /// </summary>
        internal static string WhichTarget {
            get {
                return ResourceManager.GetString("WhichTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  with the content : .
        /// </summary>
        internal static string WithContent {
            get {
                return ResourceManager.GetString("WithContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à with parameters .
        /// </summary>
        internal static string WithParameters {
            get {
                return ResourceManager.GetString("WithParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  with the data : .
        /// </summary>
        internal static string WithTheData {
            get {
                return ResourceManager.GetString("WithTheData", resourceCulture);
            }
        }
    }
}
