//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomUpdateCreator.Localization {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CustomUpdateCreatorStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CustomUpdateCreatorStrings() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CustomUpdateCreator.Localization.CustomUpdateCreatorStrings", typeof(CustomUpdateCreatorStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An Action store its return code in the variable but the update returns a static code..
        /// </summary>
        internal static string ActionWithReturnCodeAndUpdateWithStaticMethod {
            get {
                return ResourceManager.GetString("ActionWithReturnCodeAndUpdateWithStaticMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error occurs while initializing : .
        /// </summary>
        internal static string AnErrorOccursWhileIntializingAction {
            get {
                return ResourceManager.GetString("AnErrorOccursWhileIntializingAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error occurs while saving Template : .
        /// </summary>
        internal static string AnErrorOccursWhileSavingTemplate {
            get {
                return ResourceManager.GetString("AnErrorOccursWhileSavingTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unable to create an isntance of this Action : .
        /// </summary>
        internal static string CannotCreateAnInstanceOfThisAction {
            get {
                return ResourceManager.GetString("CannotCreateAnInstanceOfThisAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cannot find the file : .
        /// </summary>
        internal static string CannotFindTheFile {
            get {
                return ResourceManager.GetString("CannotFindTheFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Xml element &apos;CustomActionTemplate&apos; cannot be found..
        /// </summary>
        internal static string CustomUpdateFileBadlyFormated {
            get {
                return ResourceManager.GetString("CustomUpdateFileBadlyFormated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you want to save the current Custom Update ?.
        /// </summary>
        internal static string DoYouWantToSaveCurrentCustomUpdate {
            get {
                return ResourceManager.GetString("DoYouWantToSaveCurrentCustomUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error occurs while loading Template : .
        /// </summary>
        internal static string ErrorLoadingTemplate {
            get {
                return ResourceManager.GetString("ErrorLoadingTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à It will have default value..
        /// </summary>
        internal static string ItWillHaveDefaultValues {
            get {
                return ResourceManager.GetString("ItWillHaveDefaultValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à There is more than one Action to store its return code into the variable..
        /// </summary>
        internal static string MoreThanOneActionWithReturnCode {
            get {
                return ResourceManager.GetString("MoreThanOneActionWithReturnCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Move Down.
        /// </summary>
        internal static string MoveDown {
            get {
                return ResourceManager.GetString("MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Move Up.
        /// </summary>
        internal static string MoveUp {
            get {
                return ResourceManager.GetString("MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A Custom Update must have, at least, one Action..
        /// </summary>
        internal static string NoActionInThisCustomUpdate {
            get {
                return ResourceManager.GetString("NoActionInThisCustomUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saved.
        /// </summary>
        internal static string saved {
            get {
                return ResourceManager.GetString("saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A Custom Update that returns the contains of the variable must have an action that store its return code in the variable..
        /// </summary>
        internal static string TheVariableIsNeverFill {
            get {
                return ResourceManager.GetString("TheVariableIsNeverFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This Action has not been recognized : .
        /// </summary>
        internal static string ThisActionHasNotBeenRecognized {
            get {
                return ResourceManager.GetString("ThisActionHasNotBeenRecognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This Action is not properly configurated..
        /// </summary>
        internal static string ThisActionIsNotProperlyConfigurated {
            get {
                return ResourceManager.GetString("ThisActionIsNotProperlyConfigurated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unable to set ReturnCode from the Template..
        /// </summary>
        internal static string UnableToSetReturnCodeFromXmlFile {
            get {
                return ResourceManager.GetString("UnableToSetReturnCodeFromXmlFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à unnamed.CustAct.
        /// </summary>
        internal static string unnamed {
            get {
                return ResourceManager.GetString("unnamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unsaved.
        /// </summary>
        internal static string unsaved {
            get {
                return ResourceManager.GetString("unsaved", resourceCulture);
            }
        }
    }
}
